package com.storyteller.data.audio

import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.storyteller.domain.model.PlaybackState
import com.storyteller.domain.model.PreparedUnit
import com.storyteller.domain.model.SpeechUnit
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File
import java.nio.ByteBuffer
import java.nio.ByteOrder

@RunWith(AndroidJUnit4::class)
class PagePlayerImplTest {

    private val context = InstrumentationRegistry.getInstrumentation().targetContext

    /**
     * Synthesizes a 200ms silent WAV at runtime instead of bundling an mp3 asset
     * generated by ffmpeg (not installed on this machine). A WAV is a 44-byte
     * canonical PCM header followed by raw samples, so it is trivial to build by
     * hand: 8kHz mono 16-bit for 0.2s is 8000 * 0.2 * 2 bytes = 3200 bytes of
     * silence. ExoPlayer decodes WAV natively, so this still exercises real
     * Media3 playback of a real, if silent, media file.
     */
    private fun silence(name: String): File {
        val sampleRate = 8000
        val bitsPerSample = 16
        val channels = 1
        val durationSeconds = 0.2
        val dataSize = (sampleRate * durationSeconds * channels * (bitsPerSample / 8)).toInt()
        val byteRate = sampleRate * channels * (bitsPerSample / 8)
        val blockAlign = channels * (bitsPerSample / 8)

        val header = ByteBuffer.allocate(44).order(ByteOrder.LITTLE_ENDIAN).apply {
            put("RIFF".toByteArray())
            putInt(36 + dataSize)
            put("WAVE".toByteArray())
            put("fmt ".toByteArray())
            putInt(16) // Subchunk1Size for PCM
            putShort(1) // AudioFormat: PCM
            putShort(channels.toShort())
            putInt(sampleRate)
            putInt(byteRate)
            putShort(blockAlign.toShort())
            putShort(bitsPerSample.toShort())
            put("data".toByteArray())
            putInt(dataSize)
        }

        val out = File(context.cacheDir, name)
        out.outputStream().use { stream ->
            stream.write(header.array())
            stream.write(ByteArray(dataSize)) // silence: all-zero PCM samples
        }
        return out
    }

    private fun prepared(index: Int, file: File) = PreparedUnit(
        unit = SpeechUnit(index, "Wolf", "line $index", null),
        voiceId = "v-a",
        audio = file,
    )

    /**
     * ExoPlayer binds itself to whichever thread constructs it (its
     * "applicationLooper", which defaults to the main looper when the calling
     * thread has none) and then throws IllegalStateException if any player
     * method is later called from a different thread. The instrumentation test
     * thread has no looper of its own, so construction and every call into the
     * player must be pushed onto the main thread explicitly; only reading the
     * resulting StateFlow is safe to do from the test thread, since StateFlow
     * reads are thread-safe regardless of who updates them.
     *
     * Uses runBlocking rather than runTest: runTest fast-forwards a virtual
     * clock, but the state transition this test waits on arrives from real
     * ExoPlayer decoding and real Handler callbacks on wall-clock time, not
     * from delay() calls the virtual scheduler can see. Under runTest the
     * virtual clock found nothing left to advance and jumped straight to the
     * 10s timeout without giving playback any real time to finish.
     *
     * A bare wait-for-Finished assertion would pass identically if append()
     * were a no-op stub, since a single 200ms item alone reaches STATE_ENDED
     * well inside the timeout. So this also asserts: the final playlist holds
     * all 3 items, they became current in strict reading order (0, 1, 2), and
     * wall-clock elapsed is consistent with three ~200ms items having actually
     * played rather than just one.
     */
    @Test
    fun playsAGrowingPlaylistThroughToFinishedInOrder() = runBlocking {
        lateinit var player: PagePlayerImpl
        val instrumentation = InstrumentationRegistry.getInstrumentation()
        val start = System.nanoTime()
        instrumentation.runOnMainSync {
            player = PagePlayerImpl(context)
            player.play(listOf(prepared(0, silence("a.wav"))))
            player.append(prepared(1, silence("b.wav")))
            player.append(prepared(2, silence("c.wav")))
            player.endOfPage()
        }
        try {
            withTimeout(10_000) {
                assertEquals(PlaybackState.Finished, player.state.first { it == PlaybackState.Finished })
            }
            val elapsedMs = (System.nanoTime() - start) / 1_000_000
            // Nominal total is 3 * 200ms = 600ms; a generous lower bound well
            // under that avoids flaking on real hardware while still failing
            // if only one item's worth of playback actually happened.
            assertTrue("expected >=3 items worth of playback, took ${elapsedMs}ms", elapsedMs >= 450)

            var count = -1
            var visited = emptyList<Int>()
            instrumentation.runOnMainSync {
                count = player.mediaItemCountForTest
                visited = player.visitedMediaItemIndicesForTest
            }
            assertEquals(3, count)
            assertEquals(listOf(0, 1, 2), visited)
        } finally {
            instrumentation.runOnMainSync { player.release() }
        }
    }

    /**
     * Proves Critical B's fix: append() exists precisely so audio starts
     * before the page finishes synthesizing, which means item 0 finishing
     * playback before item 1's synthesis lands is the normal case, not an
     * edge case. Without endOfPage() gating STATE_ENDED, the player cannot
     * tell "temporarily starved, more coming" from "genuinely done" and would
     * latch Finished the moment item 0 alone runs out — stranding items still
     * to arrive. This test waits well past item 0's 200ms runtime before
     * appending item 1, asserts the state has NOT prematurely finished during
     * that starved gap, then confirms Finished only arrives after endOfPage()
     * once item 1 actually completes.
     */
    @Test
    fun staysPlayingWhileStarvedAndOnlyFinishesAfterEndOfPage() = runBlocking {
        lateinit var player: PagePlayerImpl
        val instrumentation = InstrumentationRegistry.getInstrumentation()
        instrumentation.runOnMainSync {
            player = PagePlayerImpl(context)
            player.play(listOf(prepared(0, silence("a.wav"))))
        }
        try {
            // item 0 is a 200ms clip, but measured on-device logcat timestamps
            // (STATE_BUFFERING -> STATE_READY -> STATE_ENDED) showed local WAV
            // prepare/buffer latency alone costs ~325ms before playback even
            // starts, so ENDED naturally lands around ~540ms after play(), not
            // ~200ms. A 400ms margin was tried first and produced a false pass
            // when the fix was reverted: STATE_ENDED simply hadn't fired yet at
            // the 400ms mark, so the assertion below held regardless of whether
            // the gating fix was present, and it was proving nothing. 1000ms
            // leaves a safe margin above the measured ~540ms for device
            // variance while still keeping the test fast.
            delay(1000)
            assertEquals(
                "playlist merely ran dry pending more units; must not be Finished yet",
                PlaybackState.Playing,
                player.state.value,
            )

            instrumentation.runOnMainSync {
                player.append(prepared(1, silence("b.wav")))
                player.endOfPage()
            }

            withTimeout(10_000) {
                assertEquals(PlaybackState.Finished, player.state.first { it == PlaybackState.Finished })
            }
        } finally {
            instrumentation.runOnMainSync { player.release() }
        }
    }
}
