package com.storyteller.data.audio

import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.storyteller.domain.model.PlaybackState
import com.storyteller.domain.model.PreparedUnit
import com.storyteller.domain.model.SpeechUnit
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import org.junit.Assert.assertEquals
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File
import java.nio.ByteBuffer
import java.nio.ByteOrder

@RunWith(AndroidJUnit4::class)
class PagePlayerImplTest {

    private val context = InstrumentationRegistry.getInstrumentation().targetContext

    /**
     * Synthesizes a 200ms silent WAV at runtime instead of bundling an mp3 asset
     * generated by ffmpeg (not installed on this machine). A WAV is a 44-byte
     * canonical PCM header followed by raw samples, so it is trivial to build by
     * hand: 8kHz mono 16-bit for 0.2s is 8000 * 0.2 * 2 bytes = 3200 bytes of
     * silence. ExoPlayer decodes WAV natively, so this still exercises real
     * Media3 playback of a real, if silent, media file.
     */
    private fun silence(name: String): File {
        val sampleRate = 8000
        val bitsPerSample = 16
        val channels = 1
        val durationSeconds = 0.2
        val dataSize = (sampleRate * durationSeconds * channels * (bitsPerSample / 8)).toInt()
        val byteRate = sampleRate * channels * (bitsPerSample / 8)
        val blockAlign = channels * (bitsPerSample / 8)

        val header = ByteBuffer.allocate(44).order(ByteOrder.LITTLE_ENDIAN).apply {
            put("RIFF".toByteArray())
            putInt(36 + dataSize)
            put("WAVE".toByteArray())
            put("fmt ".toByteArray())
            putInt(16) // Subchunk1Size for PCM
            putShort(1) // AudioFormat: PCM
            putShort(channels.toShort())
            putInt(sampleRate)
            putInt(byteRate)
            putShort(blockAlign.toShort())
            putShort(bitsPerSample.toShort())
            put("data".toByteArray())
            putInt(dataSize)
        }

        val out = File(context.cacheDir, name)
        out.outputStream().use { stream ->
            stream.write(header.array())
            stream.write(ByteArray(dataSize)) // silence: all-zero PCM samples
        }
        return out
    }

    private fun prepared(index: Int, file: File) = PreparedUnit(
        unit = SpeechUnit(index, "Wolf", "line $index", null),
        voiceId = "v-a",
        audio = file,
    )

    /**
     * ExoPlayer binds itself to whichever thread constructs it (its
     * "applicationLooper", which defaults to the main looper when the calling
     * thread has none) and then throws IllegalStateException if any player
     * method is later called from a different thread. The instrumentation test
     * thread has no looper of its own, so construction and every call into the
     * player must be pushed onto the main thread explicitly; only reading the
     * resulting StateFlow is safe to do from the test thread, since StateFlow
     * reads are thread-safe regardless of who updates them.
     *
     * Uses runBlocking rather than runTest: runTest fast-forwards a virtual
     * clock, but the state transition this test waits on arrives from real
     * ExoPlayer decoding and real Handler callbacks on wall-clock time, not
     * from delay() calls the virtual scheduler can see. Under runTest the
     * virtual clock found nothing left to advance and jumped straight to the
     * 10s timeout without giving playback any real time to finish.
     */
    @Test
    fun playsAGrowingPlaylistThroughToFinished() = runBlocking {
        lateinit var player: PagePlayerImpl
        val instrumentation = InstrumentationRegistry.getInstrumentation()
        instrumentation.runOnMainSync {
            player = PagePlayerImpl(context)
            player.play(listOf(prepared(0, silence("a.wav"))))
            player.append(prepared(1, silence("b.wav")))
            player.append(prepared(2, silence("c.wav")))
        }
        try {
            withTimeout(10_000) {
                assertEquals(PlaybackState.Finished, player.state.first { it == PlaybackState.Finished })
            }
        } finally {
            instrumentation.runOnMainSync { player.release() }
        }
    }
}
